bazel/astore: add logic to retry failed download commands.
This commit adds logic in astore_package and astore_file to retry
the astore command up to a configurable amount of times, with a sleep
in between. It defaults to 10 times, with a 1 second sleep.

TESTED:
/home/carlo/enkit -> contains the modified version of the rule.

1) bazel build --override_repository=enkit=/home/carlo/enkit @aspect_cli//:all

    Fetching repository @com_gcc_arm_none_eabi_compiler; attempt #1, fetching...

See "attempt #1" showing that the logic is invoked. Note that although I'm rebuilding
@aspect_cli, the change in repository rule definition is causing the re-evaluation
of all targets using it.

2) injected a fatal failure by manually changing the path of "enkit" to "enkot", and tried the same:

ERROR: Error computing the main repository mapping: no such package '@io_bazel_stardoc//': astore download failed after 10 attempts - GIVING UP. Here's the output of each run:
Attempt 1 failed with:
Command: enkot astore download --force-uid nudhexv23e5qqhex6cbhs55f2so6xpwo --output /home/carlo/.cache/bazel/_bazel_carlo/2704969d7f09c4c6f79647b2534900eb/external/io_bazel_stardoc/stardoc-0.5.0.tar.gz --overwrite
Stdout:

Stderr:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(enkot, ...)": No such file or directory
[...]
Attempt 10 failed with:
Command: enkot astore download --force-uid nudhexv23e5qqhex6cbhs55f2so6xpwo --output /home/carlo/.cache/bazel/_bazel_carlo/2704969d7f09c4c6f79647b2534900eb/external/io_bazel_stardoc/stardoc-0.5.0.tar.gz --overwrite
Stdout:

Stderr:
src/main/tools/process-wrapper-legacy.cc:80: "execvp(enkot, ...)": No such file or directory

Output shows 10 attempts, all failing, and shows the bazel overall download failing, as desired.
Timestamps (not shown in the final output here) also show the sleep working correctly.

3) Put back "enkit" as enkit_args[0] after one failure, in the for loop.

See "attempt #2" in the output (was not fast enough with my cut and paste game),
see the build succeeding overall.