fix: make grpc use hermetic python headers (#1115)
TL;DR - This patch should fix the issue that pops up from time to time
where grpc's python stuff breaks due to having python 3.12 installed on
the system.

Going forward we should try to stamp out our usage of `python_configure`
and `local_config_python`. This is a step in that direction.

### Technical details

After filling up my disk I had to `bazel clean --expunge` and started
noticing some interesting side effects -

My builds started failing with a familiar error where grpc picks up
python 3.12 headers which have an API break:
```sh
bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp: In function 'size_t __Pyx_PyInt_As_size_t(PyObject*)':
bazel-out/k8-fastbuild/bin/external/com_github_grpc_grpc/src/python/grpcio/grpc/_cython/cygrpc.cpp:132754:55: error: 'PyLongObject' {aka 'struct _longobject'} has no member named 'ob_digit'
132754 |             const digit* digits = ((PyLongObject*)x)->ob_digit;
```

Sure enough running `python --version` on my system indicated that I was
running `3.12`. I uninstalled this python - but that made bazel *very*
unhappy:
```sh
ERROR: /bazel/paths/to/external/local_config_python/_python/BUILD:75:8 declares output /some/path/Python.h is a dangling symbolic link
```

So it appears that although we have a hermetic python toolchain setup -
`local_config_python` is still configuring targets based on the python
headers it's able to find on the system. In my case I installed python
3.12 sometime before I `clean --expunged` and this time around it picked
up the headers that make grpc break.

I found at least two different dependencies of ours that try to create
this dependency:
-
https://github.com/pybind/pybind11_bazel/blob/fd7d88857cca3d7435b06f3ac6abab77cd9983b2/python_configure.bzl#L431
-
https://github.com/grpc/grpc/blob/b39ffcc425ea990a537f98ec6fe6a1dcb90470d7/third_party/py/python_configure.bzl#L379

luckily `rules_python` provides equivalents for the targets contained in
`local_config_python` - so fixing this is a matter of making our builds
use those instead.

I tried to globally shadow the `local_config_python` targets with the
`rules_python` versions but ran into a lot of friction. In the end I
just patched the specific usage in `grpc` that was causing the failures.

For pybind11 - we just need to upgrade:
https://github.com/pybind/pybind11_bazel/pull/72

grpc is also trying to get a fix landed it looks like:
https://github.com/grpc/grpc/pull/35666