bazel/utils: allow multiple transform rules to work within the same package.
Background:
transform() rules need a support script, transformer.sh, expanded
differently for each use of the rule.

The current transform() implementation has a declare_file that always
generates a file named transformer.sh (hard coded).

When two rules in the same package both use transform, bazel ends
up complaining that two different things are generating the same
file:

ERROR: file '....sh' is generated by these conflicting actions:
Label: //.../whatever:rule1, //.../whatever:rule2

According to bazel best practices, to solve this problem it is
sufficient to prepend (or append, or whatever) the label name
in generated files, so the name is unique.

In this PR:
- prepend the label.name to generated files.