bazel/meson: fix missing Meson python files
The meson filegroup was defined incorrectly leading to this error:

ModuleNotFoundError: No module named 'mesonbuild'

Jira: https://enfabrica.atlassian.net/browse/SF-202
Signed-off-by: George Prekas <george@enfabrica.net>