bazel/astore: fix integration errors (#777)
bazel/astore: fix integration errors

presubmits for the integration PR uncovered a surprising error:

* https://github.com/enfabrica/internal/pull/9321
* https://console.cloud.google.com/cloud-build/builds/7ed83bd9-dae0-4482-bc2a-2d36a5653dd2;step=6?project=cloud-build-290921

An example error message:

```
ERROR: /tmp/git_temp_worktree_2097900939/hw/projects/mlm/design/chip/macro_gen/BUILD:10940:14:
every rule of type astore_upload implicitly depends upon the target
'@enkit//bazel/astore:astore_upload_file.sh', but this target could not be
found because of: error loading package '@enkit//bazel/astore': Label
'//bazel/astore:defs.bzl' is invalid because 'bazel/astore' is not a package;
perhaps you meant to put the colon here: '//bazel:astore/defs.bzl'?`
```

The issue is resolved by adding a bzl_library rule to bazel/astore/BUILD.bazel, verified by running

```
bazel query --override_repository=enkit=/home/jonathan/gee/enkit/bazel_astore_cleanup  'deps (//bazel/dependencies/...)'
```

I'm a little confused as to why this error didn't exist before my PR as well,
but -- shrug!  At least this PR fixes it.

While I was debugging this, I moved the test rules to a test subdirectory, and
replaced the boring test data file with a poem.

Tested: See above.  I also re-ran my manual tests:

```
cd bazel/astore/tests
blaze run :test_astore_upload_file  # upload a new version and update UID
blaze build $(blaze query :all)  # run the various astore_download rules
```