linux/defs.bzl: Use enkit auth for kernel_tree_version
While ctx.download_and_extract() does support a basic auth scheme and
one via .netrc, neither of those models match enkit proxy's auth model.
It is desirable to avoid the need for public URLs for artifacts that are
pushed to astore, so this commit uses the enkit CLI to directly fetch
the artifacts using enkit auth. The astore_download_and_extract function
is modeled after the astore_package rule in our internal repo.

Testing: Without proper authentication, I get the following error when
trying to build a kernel driver target (while overriding enkit to slurp
in this change).

```
Stderr:
ERROR: Attempting to use your credentials failed with:
    (for debug only) rpc error: code = Unauthenticated desc = invalid credentials - signature expired

This probably means that you just need to log in again with:
        enkit login raghu@enfabrica.net
```

The same build succeeds once I authenticate with my credentials. Also
tested rogue targets which provide both a URL and a path and see
expected behavior.

Jira: INFRA-1027

Signed-off-by: Raghu Raja <raghu@enfabrica.net>