enkit: improve enkit agent error message (#773)
enkit: improve enkit agent error message

One time while logging in I saw the following message:

```
2022-10-04T16:12:08.202Z        WARN    error saving credentials, err: symlink /tmp/ssh-wKEavpGmnw/agent.41963 /home/jonathan/.config/enkit/agent: file exists
ERROR: symlink /tmp/ssh-wKEavpGmnw/agent.41963 /home/jonathan/.config/enkit/agent: file exists
```

Everything seemed to work, but this message wasn't sufficient for me to debug
the code, especially since we're never performing the operation in question.
Nothing seems broken, but let's improve the error messages anyway so we can
root cause this properly in the future.

Tested: All existing tests still pass.