gee: improve handling of updated/deleted merge conflicts (#1040)
gee: improve handling of updated/deleted merge conflicts

gee tries to use `git checkout` to select between "ours" and "theirs" when
resolving merge conflicts.  This fails to work when the file has been updated
in one branch and deleted in the other branch: the git command terminates with
a non-zero exit code, causing gee to abort with an error and leaving the user
in a merge-in-progress state.

This PR improves the behavior by detecting this condition and invoking `git mergetool`
to resolve the updated/deleted merge conflict.  (there are other ways to resolve this
merge conflict but `git mergetool` was the cleanest.)

Tested:

I created two branches: test1 and test2.  In branch test1, I modified CODEOWNERS.  In branch
test2, I deleted CODEOWNERS.

Behavior before this fix:

```
$ gcd test1
$ gee set_parent test2
test2 is the parent branch of test1
$ gee up
no pull requests found for branch "jonathan-enf:test1"
CMD: /usr/bin/git rebase --autostash test2 test1
CONFLICT (modify/delete): CODEOWNERS deleted in HEAD and modified in 5ddd5ee (CODEOWNERS: modified).  Version 5ddd5ee (CODEOWNERS: modified) of CODEOWNERS left in tree.
error: could not apply 5ddd5ee... CODEOWNERS: modified
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 5ddd5ee... CODEOWNERS: modified
WARNING: Command /usr/bin/git rebase --autostash test2 test1 failed with exit code 1
WARNING: Rebase operation had merge conflicts.

CODEOWNERS: DU=Deleted by us
keep (Y)ours, keep (T)heirs, (M)erge, (G)ui-Merge, (V)iew, (A)bort, or (H)elp? t
CODEOWNERS: Discarding your version from 5ddd5ee CODEOWNERS: modified
CODEOWNERS: Keeping their version from 16ce0cf CODEOWNERS: deleted
Keeping older CODEOWNERS from 16ce0cf CODEOWNERS: deleted
error: path 'CODEOWNERS' does not have our version
(gee fails with an error, branch is left in a rebase-in-progress state).
```

Behavior after this fix:

```
$ gcd test1
$ gee set_parent test2
test2 is the parent branch of test1
$ gee up
no pull requests found for branch "jonathan-enf:test1"
CMD: /usr/bin/git rebase --autostash test2 test1
CONFLICT (modify/delete): CODEOWNERS deleted in HEAD and modified in 5ddd5ee (CODEOWNERS: modified).  Version 5ddd5ee (CODEOWNERS: modified) of CODEOWNERS left in tree.
error: could not apply 5ddd5ee... CODEOWNERS: modified
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 5ddd5ee... CODEOWNERS: modified
WARNING: Command /usr/bin/git rebase --autostash test2 test1 failed with exit code 1
WARNING: Rebase operation had merge conflicts.

CODEOWNERS: DU=Deleted by them
keep (Y)ours, keep (T)heirs, (M)erge, (G)ui-Merge, (V)iew, (A)bort, or (H)elp? t
CODEOWNERS: Discarding your version from 5ddd5ee CODEOWNERS: modified
CODEOWNERS: Keeping their version from 16ce0cf CODEOWNERS: deleted
Keeping older CODEOWNERS from 16ce0cf CODEOWNERS: deleted
Merging:
CODEOWNERS

Deleted merge conflict for 'CODEOWNERS':
  {local}: deleted
  {remote}: modified file
Use (m)odified or (d)eleted file, or (a)bort? CMD: /usr/bin/git add .
CMD: /usr/bin/git rebase --continue
Successfully rebased and updated refs/heads/test1.
Rebase merge confirmed.
To undo: git checkout test1; git reset --hard test1.REBASE_BACKUP
CMD: /usr/bin/git push --quiet -u origin +test1
remote:
remote: Create a pull request for 'test1' on GitHub by visiting:
remote:      https://github.com/jonathan-enf/enkit/pull/new/test1
remote:
Done.
```

I also tested the reverse flow:

```
$ gcd test2; gee set_parent test1
test1 is the parent branch of test2
$ gee up
CMD: /usr/bin/git fetch origin
no pull requests found for branch "jonathan-enf:test2"
CMD: /usr/bin/git rebase --autostash test1 test2
CONFLICT (modify/delete): CODEOWNERS deleted in 16ce0cf (CODEOWNERS: deleted) and modified in HEAD.  Version HEAD of CODEOWNERS left in tree.
error: could not apply 16ce0cf... CODEOWNERS: deleted
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 16ce0cf... CODEOWNERS: deleted
WARNING: Command /usr/bin/git rebase --autostash test1 test2 failed with exit code 1
WARNING: Rebase operation had merge conflicts.

CODEOWNERS: UD=Deleted by us
keep (Y)ours, keep (T)heirs, (M)erge, (G)ui-Merge, (V)iew, (A)bort, or (H)elp? y
CODEOWNERS: Keeping your version from 16ce0cf CODEOWNERS: deleted
CODEOWNERS: Discarding their version from 429d089 CODEOWNERS: updated
Merging:
CODEOWNERS

Deleted merge conflict for 'CODEOWNERS':
  {local}: modified file
  {remote}: deleted
Use (m)odified or (d)eleted file, or (a)bort? CMD: /usr/bin/git add .
CMD: /usr/bin/git rebase --continue
[detached HEAD bd79c3d] CODEOWNERS: deleted
 1 file changed, 1 deletion(-)
 delete mode 100644 CODEOWNERS
Successfully rebased and updated refs/heads/test2.
Rebase merge confirmed.
To undo: git checkout test2; git reset --hard test2.REBASE_BACKUP
```